### ISSUE TITLE
that wont work

### ISSUE THREAD

**Issue by KiExitDispatcher** [QwertyL0L/Snake32#1]
I dont think that will work by simply doing os.remove(sys32) i forgot the path. just rewrite this or i can make pr. really easy to do syskill

**Comment by QwertyL0L** [comment]
my virtual machine wouldnt work so i couldnt test it lol but if u wanna make a pr then go ahead

**Comment by KiExitDispatcher** [comment]
...

**Comment by QwertyL0L** [comment]
what?
